### ISSUE TITLE
Pretrained model please 

### ISSUE THREAD

**Issue by rishikksh20** [acetylSv/GST-tacotron#1]
If possible then please share pretrained models of respective datasets.

**Comment by acetylSv** [comment]
I've uploaded the pretrained models [here](http://speech.ee.ntu.edu.tw/~acetylsv/pretrained_model.zip).
Note that some hyperparameters (n_fft and sample_rate) on these two pretrained models are slightly difference as I updated in README.
Hope these models help you.

**Comment by rishikksh20** [comment]
@acetylSv  one more thing does it GST Tacotron based on Tacotron 2 architect or Tacotron 1 ?

**Comment by acetylSv** [comment]
To my understanding, the architecture of GST Tacotron is an extension of Tacotron1's.

**Comment by rishikksh20** [comment]
@acetylSv thanks

**Comment by rishikksh20** [comment]
@acetylSv As I see your TODO has wavelet_vocoder in it, does it possible to integrate Tacotron 1 with wavenet vocoder ?

**Comment by acetylSv** [comment]
Sure. The wavenet vocoder could be triained with mel spectrogram as input and raw waveform as output. So one could just replace the Griffin-Lim vocoder with a wavenet vocoder. This also means that the mel-scale spectrogram to magnitude spectrogram part in network.py could be discarded.

**Comment by ishandutta2007** [comment]
@acetylSv I checked the [samples](https://github.com/acetylSv/GST-tacotron/tree/master/samples), there is still quite a bit of vibration even after 450k odd steps.
The google's [samples](https://ai.googleblog.com/2018/03/expressive-speech-synthesis-with.html) were very smooth. Is there a difference in implementation or does it need lot more steps ?
